<a href="https://colab.research.google.com/github/yujeeb/pytorch-explorer/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 4]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

## Practice

In [ ]:
myTensor = torch.Tensor([[[12, 69, 43],
                          [12, 12, 12],
                          [65, 4, 1]],
                         [[2, 56, 12],
                          [43, 9, 0],
                          [12, 65, 14]]])
myTensor

tensor([[[12., 69., 43.],
         [12., 12., 12.],
         [65.,  4.,  1.]],

        [[ 2., 56., 12.],
         [43.,  9.,  0.],
         [12., 65., 14.]]])

In [ ]:
myTensor.ndim

3

In [ ]:
myTensor.shape

torch.Size([2, 3, 3])

In [ ]:
myTensor[1]

tensor([[ 2., 56., 12.],
        [43.,  9.,  0.],
        [12., 65., 14.]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8259, 0.6239, 0.3448, 0.6286],
        [0.6400, 0.5343, 0.2568, 0.8010],
        [0.7459, 0.2338, 0.8263, 0.4558]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Practice

my_random_tensor = torch.rand(5, 12, 14)
my_random_tensor

tensor([[[4.1090e-01, 2.1092e-01, 3.3342e-02, 2.2580e-01, 2.6218e-02,
          7.0328e-01, 1.2519e-01, 9.3264e-01, 8.2299e-01, 6.3311e-01,
          8.3268e-01, 9.5801e-01, 3.8289e-01, 9.0466e-01],
         [7.2704e-01, 7.6531e-01, 4.2706e-01, 9.7550e-02, 6.5335e-02,
          9.9792e-01, 3.4284e-01, 7.8602e-01, 6.3695e-01, 5.1295e-01,
          7.2949e-01, 6.8522e-01, 5.1917e-01, 6.9255e-01],
         [3.1628e-01, 6.3819e-01, 4.8443e-01, 7.9433e-02, 4.6412e-01,
          7.5974e-01, 9.2243e-01, 3.8126e-01, 6.6016e-01, 8.4509e-01,
          9.1940e-01, 5.9840e-01, 4.3055e-01, 7.3992e-01],
         [2.4850e-01, 4.9697e-01, 7.5454e-01, 3.5583e-01, 6.1921e-01,
          2.3402e-01, 9.4785e-02, 5.7577e-01, 2.5785e-01, 2.9173e-01,
          9.9971e-01, 5.8621e-01, 3.4106e-01, 3.5091e-01],
         [6.9769e-01, 8.1544e-01, 5.4433e-01, 3.7908e-01, 8.3041e-01,
          8.4839e-01, 3.9450e-01, 9.1194e-01, 9.8155e-01, 4.0453e-01,
          3.1473e-01, 1.9801e-01, 7.3442e-01, 4.3278e-01],
     

## Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
# Practice

my_zeros = torch.zeros(size=(10, 10))
my_ones = torch.ones(size=(5, 12, 14))

my_zeros, my_ones

(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1

### Creating a range of tensor and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

#### Practice